print("Welcome to band name generator game.!!")
name1 = input("What is your city name: ")
print('\n')
name2 = input("What is your pet name: ")
print('\n')
print("Your band name is: " + name1 +" "+ name2)
